name: tang-ci

on: [push, pull_request] 

jobs:
  Test-all-UI:
    runs-on: macOS-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: npm ci
    - name: Create a screenshot folder before test run
      run: mkdir screenshots
    - name: Running nightwatch tests
      run: npm run headless
    - name: Create a screenshot folder after test run
      run: mkdir screenshots
    - name: Upload failure screenshot artifacts
      uses: actions/upload-artifact@v2
      with:
        name: failure-screenshot
        path: screenshots
